Repository jupyterhub/action-k3s-helm, pull requests merged in 2022-08, with the labels that each got.

#64 Workaround kubectl exec and kubectl logs issues with k3s
  action.yml
Labels: maintenance

#66 Update cri-dockerd from 0.2.3 to 0.2.5
  action.yml
Labels: maintenance

#65 docs: add changelog for 3.0.1
  CHANGELOG.md
Labels: documentation

#67 Apply workaround added in 3.0.1 only when possible
  action.yml
Labels: bug

#68 Add changelog for 3.0.2
  CHANGELOG.md
Labels: documentation

#69 Fix workaround added in 3.0.1 and adjusted in 3.0.2
  action.yml
Labels: bug

#70 Add changelog for 3.0.3
  CHANGELOG.md
Labels: documentation

#71 fix: fail after 10 minutes (previously 5) as image pulling can take time
  action.yml
Labels: bug

#72 Add changelog for 3.0.4
  CHANGELOG.md
Labels: documentation

#73 Calico 3.24.0 (3.23 manifest URL is broken)
  CHANGELOG.md
  README.md
  action.yml
Labels: bug
